version: "3.9"
services:
  db:
    image: postgres:15.4
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: ${DB_DATA}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db_data:${DB_DATA}
    ports:
      - "${DB_EXPOSE_PORT}:5432"

  backend:
    container_name: backend
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    command: >
      bash -c "alembic upgrade head && python3 src/pwe/main.py"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
