name: pwe-build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
 test:
    environment: test

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Создание .env файла
      run: |
          echo "${{ secrets.ENV_FILE }}" > .env
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Проверка кода с помощью flake8
      run: |
        flake8 src
    - name: Тесты pytest
      run: |
        pytest
 prepare-environment:
     runs-on: self-hosted
     needs: test
     environment: production
     steps:
       - name: Проверка репозитория
         uses: actions/checkout@v3
       - name: Создание .env файла
         run: |
          echo "${{ secrets.ENV_FILE }}" > .env
       - name: Остановка и удаление прошлых контейнеров
         run: docker compose down
       - name: Удаление неиспользуемых данных
         run: docker system prune -a -f
 deploy:
     runs-on: self-hosted
     needs: prepare-environment
     steps:
       - name: docker compose
         run: docker compose up -d
