name: pwe-build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
 test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with flake8
      run: |
        flake8 ./src
    - name: Test with pytest
      run: |
        pytest
 prepare-environment:
     runs-on: self-hosted
     needs: test
     steps:
       - name: Stop and remove containers, networks
         run: docker-compose down
       - name: Remove unused data
         run: docker system prune -a -f
 deploy:
     runs-on: self-hosted
     needs: prepare-environment
     steps:
       - name: checkout repo
         uses: actions/checkout@v3
       - name: docker-compose
         run: docker-compose up -d
