name: pwe-build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
 test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Установка Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Создание .env файла
      run: |
          echo "${{ production.ENV_FILE }}" > .env
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
    - name: Проверка кода с помощью flake8
      run: |
        flake8 src
    - name: Тесты pytest
      run: |
        pytest
 prepare-environment:
     runs-on: self-hosted
     needs: test
     steps:
       - name: Остановка и удаление прошлых контейнеров
         run: docker-compose down
       - name: Удаление неиспользуемых данных
         run: docker system prune -a -f
 deploy:
     runs-on: self-hosted
     needs: prepare-environment
     steps:
       - name: checkout repo
         uses: actions/checkout@v3
       - name: docker-compose
         run: docker-compose up -d
